### ISSUE TITLE
libtool --version not working on OSX in libtool v2.4.6-1005

### ISSUE THREAD

**Issue by sebastian-luna-valero** [conda-forge/libtool-feedstock#24]
Hi,

We are updating another `conda-forge` recipe here:

https://github.com/conda-forge/gnuastro-feedstock/pull/5

This recipe depends on `libtool` and it's using the latest available version.

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=206304&view=logs&j=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&t=933f325c-924e-533d-4d95-e93b5843ce8b&l=1017

However, something may have change that prevents `libtool --version` from working on the OSX build. Please see:

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=206304&view=logs&j=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&t=933f325c-924e-533d-4d95-e93b5843ce8b&l=1087

Could you please let us know your thoughts?

Best regards,
Sebastian

**Comment by isuruf** [comment]
cc @beckermr, `libtool` is conflicting with `cctools`

**Comment by beckermr** [comment]
OK. We can backout the offending PR for sure. I was trying to solve another problem someplace else.

**Comment by beckermr** [comment]
I think https://github.com/conda-forge/clang-compiler-activation-feedstock/pull/35 will fix this, but I am not 100% sure.

**Comment by beckermr** [comment]
Can we try this again and see if the bug above is fixed?

**Comment by sebastian-luna-valero** [comment]
This is working now, thank you very much!
